version: '3.8'

services:
  # =============================================
  # DATABASE - PostgreSQL
  # =============================================
  postgres:
    image: postgres:15-alpine
    container_name: sales-postgres
    restart: unless-stopped
    
    environment:
      POSTGRES_DB: sales_automation
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SalesAuto2025!}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    
    ports:
      - "5432:5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sales_user -d sales_automation"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =============================================
  # CACHE - Redis
  # =============================================
  redis:
    image: redis:7-alpine
    container_name: sales-redis
    restart: unless-stopped
    
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    
    volumes:
      - redis_data:/data
    
    ports:
      - "6379:6379"
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
